import { M1887_CONFIG } from './weaponContent';
import { CROSSBOW_CONFIG } from './crossbowContent';
import { COMBAT_CONFIG } from './combatConfig';
import { ARCHETYPE_WEAPONS } from './archetype';
import { CYBERWARE_SLOTS } from './cyberware';

export type ItemType = 'weapon' | 'consumable' | 'material' | 'equipment' | 'key';

/** Weapon/Core category as used by the hotbar and progression systems. */
export type WeaponCategory = 'sword' | 'gun' | 'core' | 'dagger' | 'staff';

/** Armour equipment slots (four-piece armour system). */
export type ArmourSlot = 'helmet' | 'chest' | 'leggings' | 'boots';

/** Authoritative armour slot of an item id (metadata.armourSlot wins; the
 *  legacy leather cuirass defaults to chest). */
export function armourSlotOf(itemId: string | null): ArmourSlot | null {
  if (!itemId) return null;
  const def = getItem(itemId);
  if (!def?.metadata?.armour) return null;
  const slot = def.metadata.armourSlot;
  if (slot === 'helmet' || slot === 'chest' || slot === 'leggings' || slot === 'boots') return slot;
  return 'chest';
}

/** Category of a weapon/Core item id (authoritative mapping). */
export function weaponCategoryOf(itemId: string | null): WeaponCategory | null {
  switch (itemId) {
    case 'iron_sword':
    case 'wooden_sword':
      return 'sword';
    case 'dual_dagger':
      return 'dagger';
    case 'm1887':
    case 'crossbow':
      return 'gun';
    case 'resonance_core':
      return 'core';
    case 'water_staff':
    case 'all_for_staff':
      return 'staff';
    default:
      return null;
  }
}

/** Display classification for the inventory's Ranged grouping: guns and the
 *  Water Staff. Combat classification stays authoritative in
 *  weaponCategoryOf — the staff keeps its own 'staff' category so the mage
 *  spell path and the M1887 gun path remain distinct. */
export function isRangedCategory(itemId: string | null): boolean {
  const wc = weaponCategoryOf(itemId);
  return wc === 'gun' || wc === 'staff';
}

export type ItemRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

export interface ItemDef {
  id: string;
  name: string;
  description: string;
  rarity: ItemRarity;
  icon: string;
  type: ItemType;
  maxStack: number;
  value: number;
  metadata?: Record<string, unknown>;
  /** M2D1 #1 — per-item placeholder, always 0. Runtime mastery lives on
   *  player.mastery[itemId] and is never read from here. */
  mastery: number;
  /** M2D1 #1 — multiplicative melee attack speed (1.0 = neutral, 0 = N/A). */
  attackSpeed: number;
  /** M2D1 #1 — shots per second while the trigger is held (0 = N/A). */
  rateOfFireHold: number;
  /** M2D1 #1 — shots per second per click (0 = N/A). */
  rateOfFireClick: number;
  /** M2D1 #1 — stamina multiplier for this weapon (1.0 = neutral, 0 = N/A). */
  staminaUsage: number;
  /** M2D1 #1 — archetype this item was designed for ('' when unset). */
  archetypeFit: string;
  weightGrams: number;
}

export const RARITY_COLORS: Record<ItemRarity, string> = {
  common: '#9ca3af',
  uncommon: '#22c55e',
  rare: '#3b82f6',
  epic: '#a855f7',
  legendary: '#f59e0b',
};

/** Archetype a weapon was designed for ('' when no archetype claims it).
 *  Derived from the authoritative ARCHETYPE_WEAPONS table (M2D1 #1). */
function archetypeFitFor(itemId: string): string {
  if (ARCHETYPE_WEAPONS.fighter.includes(itemId)) return 'fighter';
  if (ARCHETYPE_WEAPONS.mage.includes(itemId)) return 'mage';
  return '';
}

const ITEMS: Record<string, ItemDef> = {
  wooden_sword: {
    id: 'wooden_sword',
    mastery: 0,
    attackSpeed: 1,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: COMBAT_CONFIG.dodgeStaminaCost,
    archetypeFit: archetypeFitFor('wooden_sword'),
    weightGrams: 1000,
    name: 'Wooden Sword',
    description: 'A basic training sword. Better than nothing.',
    rarity: 'common',
    icon: 'Sword',
    type: 'weapon',
    maxStack: 1,
    value: 10,
  },
  iron_sword: {
    id: 'iron_sword',
    mastery: 0,
    attackSpeed: 1,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: COMBAT_CONFIG.dodgeStaminaCost,
    archetypeFit: archetypeFitFor('iron_sword'),
    weightGrams: 1500,
    name: 'Iron Sword',
    description: 'A sturdy iron blade forged by a master blacksmith.',
    rarity: 'uncommon',
    icon: 'Sword',
    type: 'weapon',
    maxStack: 1,
    value: 80,
  },
  health_potion: {
    id: 'health_potion',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 300,
    name: 'Health Potion',
    description: 'Restores 40 HP. A staple for any adventurer.',
    rarity: 'uncommon',
    icon: 'FlaskConical',
    type: 'consumable',
    maxStack: 256,
    value: 30,
    metadata: { healAmount: 40 },
  },
  small_potion: {
    id: 'small_potion',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 150,
    name: 'Small Potion',
    description: 'Restores 25 HP. A cheaper alternative for minor wounds.',
    rarity: 'common',
    icon: 'FlaskRound',
    type: 'consumable',
    maxStack: 256,
    value: 15,
    metadata: { healAmount: 25 },
  },
  bread: {
    id: 'bread',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 400,
    name: 'Bread',
    description: 'Restores 20 HP. Simple but filling.',
    rarity: 'common',
    icon: 'Wheat',
    type: 'consumable',
    maxStack: 256,
    value: 5,
    metadata: { healAmount: 20 },
  },
  apple: {
    id: 'apple',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 150,
    name: 'Apple',
    description: 'Restores 15 HP. A quick snack from the orchard.',
    rarity: 'common',
    icon: 'Apple',
    type: 'consumable',
    maxStack: 256,
    value: 3,
    metadata: { healAmount: 15 },
  },
  iron_ore: {
    id: 'iron_ore',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 2000,
    name: 'Iron Ore',
    description: 'Raw iron recovered from bandit gear. Used for forging.',
    rarity: 'uncommon',
    icon: 'Gem',
    type: 'material',
    maxStack: 256,
    value: 20,
  },
  arcane_shard: {
    id: 'arcane_shard',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 100,
    name: 'Arcane Shard',
    description: 'A fragment of crystallized magic energy.',
    rarity: 'rare',
    icon: 'Sparkles',
    type: 'material',
    maxStack: 256,
    value: 50,
  },
  water_staff: {
    id: 'water_staff',
    mastery: 0,
    attackSpeed: 1,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: COMBAT_CONFIG.dodgeStaminaCost,
    archetypeFit: archetypeFitFor('water_staff'),
    weightGrams: 2000,
    name: 'Water Staff',
    description: 'A runed staff that channels water magic. Ranged, precise, patient.',
    rarity: 'uncommon',
    icon: 'Wand2',
    type: 'weapon',
    maxStack: 1,
    value: 75,
  },
  dual_dagger: {
    id: 'dual_dagger',
    mastery: 0,
    attackSpeed: 1,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: COMBAT_CONFIG.dodgeStaminaCost,
    archetypeFit: archetypeFitFor('dual_dagger'),
    weightGrams: 600,
    name: 'Dual Daggers',
    description: 'A matched pair of quick blades. Blued steel in the left hand, bright in the right.',
    rarity: 'uncommon',
    icon: 'Swords',
    type: 'weapon',
    maxStack: 1,
    value: 60,
  },
  // ── Marcus Shop Food Items ───────────────────────────────────
  crispy_chicken: {
    id: 'crispy_chicken',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 500,
    name: 'Crispy Chicken',
    description: 'Golden fried chicken with a crunchy coating. Heals 30 HP.',
    rarity: 'common',
    icon: 'UtensilsCrossed',
    type: 'consumable',
    maxStack: 256,
    value: 12,
    metadata: { healAmount: 30 },
  },
  chicken_steak: {
    id: 'chicken_steak',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 400,
    name: 'Chicken Steak',
    description: 'Juicy grilled chicken breast. Heals 35 HP.',
    rarity: 'common',
    icon: 'UtensilsCrossed',
    type: 'consumable',
    maxStack: 256,
    value: 15,
    metadata: { healAmount: 35 },
  },
  beef_steak: {
    id: 'beef_steak',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 500,
    name: 'Beef Steak',
    description: 'A thick, sizzling beef steak. Heals 50 HP.',
    rarity: 'uncommon',
    icon: 'UtensilsCrossed',
    type: 'consumable',
    maxStack: 256,
    value: 22,
    metadata: { healAmount: 50 },
  },
  chicken_katsu: {
    id: 'chicken_katsu',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 550,
    name: 'Chicken Katsu',
    description: 'Crispy breaded chicken cutlet. Heals 40 HP.',
    rarity: 'common',
    icon: 'UtensilsCrossed',
    type: 'consumable',
    maxStack: 256,
    value: 18,
    metadata: { healAmount: 40 },
  },
  kebab: {
    id: 'kebab',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 450,
    name: 'Kebab',
    description: 'Grilled skewer of seasoned meat. Heals 28 HP.',
    rarity: 'common',
    icon: 'UtensilsCrossed',
    type: 'consumable',
    maxStack: 256,
    value: 10,
    metadata: { healAmount: 28 },
  },
  shawarma: {
    id: 'shawarma',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 500,
    name: 'Shawarma',
    description: 'Rolled flatbread with spiced meat and sauce. Heals 32 HP.',
    rarity: 'common',
    icon: 'UtensilsCrossed',
    type: 'consumable',
    maxStack: 256,
    value: 14,
    metadata: { healAmount: 32 },
  },
  m1887: {
    id: 'm1887',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: M1887_CONFIG.shotsPerSecond,
    staminaUsage: COMBAT_CONFIG.dodgeStaminaCost,
    archetypeFit: '',
    weightGrams: 3600,
    name: 'M1887',
    description: 'Lever-action shotgun. 2 shells, 8 pellets, devastating up close.',
    rarity: 'rare',
    icon: 'Crosshair',
    type: 'weapon',
    maxStack: 1,
    value: 220,
    metadata: { weaponCategory: 'gun', ammoCapacity: 2 },
  },
  crossbow: {
    id: 'crossbow',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 1 / CROSSBOW_CONFIG.fireIntervalHold,
    rateOfFireClick: 1 / CROSSBOW_CONFIG.fireIntervalClick,
    staminaUsage: COMBAT_CONFIG.dodgeStaminaCost,
    archetypeFit: '',
    weightGrams: 2800,
    name: 'Crossbow',
    description: 'A weighted hunting crossbow. 16 arrows per supply, 3.5 arrows per second (click) / 2 arrows per second (hold). Skins: Triplex Lactus / Mimique de Ametralladora.',
    rarity: 'rare',
    icon: 'Target',
    type: 'weapon',
    maxStack: 1,
    value: 200,
    metadata: { weaponCategory: 'gun', ammoCapacity: 16, ranged: true },
  },
  resonance_core: {
    id: 'resonance_core',
    mastery: 0,
    attackSpeed: 1,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: COMBAT_CONFIG.dodgeStaminaCost,
    archetypeFit: '',
    weightGrams: 800,
    name: 'Resonance Core',
    description: 'A conceptual Abyssal Core attuned to vibration and harmonic frequency.',
    rarity: 'epic',
    icon: 'Orbit',
    type: 'equipment',
    maxStack: 8,
    value: 300,
    metadata: { weaponCategory: 'core', coreType: 'conceptual', coreConcept: 'resonance' },
  },
  thornback_spine: {
    id: 'thornback_spine',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 1500,
    name: 'Thornback Spine',
    description: 'A barbed spine shed by a Thornback. Prized by crafters.',
    rarity: 'uncommon',
    icon: 'Bone',
    type: 'material',
    maxStack: 64,
    value: 18,
  },
  arrow_bundle: {
    id: 'arrow_bundle',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 800,
    name: 'Arrow Bundle',
    description: 'A bundle of 8 crossbow arrows. Restores ammunition when picked up (up to the crossbow capacity).',
    rarity: 'common',
    icon: 'MoveVertical',
    type: 'consumable',
    maxStack: 64,
    value: 10,
    metadata: { arrows: 8 },
  },
  leather_armour: {
    id: 'leather_armour',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 5000,
    name: 'Leather Armour',
    description: 'Hardened leather cuirass. Reduces incoming damage by 5%.',
    rarity: 'uncommon',
    icon: 'Shield',
    type: 'equipment',
    maxStack: 1,
    value: 90,
    metadata: { armour: true, damageReduction: 0.05, armourSlot: 'chest', bodyRegion: 'torso' },
  },
  iron_helmet: {
    id: 'iron_helmet',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 2000,
    name: 'Iron Helmet',
    description: 'Forged iron helm. Reduces incoming damage by 2%.',
    rarity: 'uncommon',
    icon: 'HardHat',
    type: 'equipment',
    maxStack: 1,
    value: 60,
    metadata: { armour: true, damageReduction: 0.02, armourSlot: 'helmet', bodyRegion: 'head' },
  },
  iron_leggings: {
    id: 'iron_leggings',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 4000,
    name: 'Iron Leggings',
    description: 'Plated iron greaves. Reduces incoming damage by 3%.',
    rarity: 'uncommon',
    icon: 'Footprints',
    type: 'equipment',
    maxStack: 1,
    value: 70,
    metadata: { armour: true, damageReduction: 0.03, armourSlot: 'leggings', bodyRegion: 'legs' },
  },
  iron_boots: {
    id: 'iron_boots',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 1500,
    name: 'Iron Boots',
    description: 'Heavy reinforced boots. Reduces incoming damage by 2%.',
    rarity: 'uncommon',
    icon: 'Footprints',
    type: 'equipment',
    maxStack: 1,
    value: 55,
    metadata: { armour: true, damageReduction: 0.02, armourSlot: 'boots', bodyRegion: 'feet' },
  },
  // ── M2D1 #2 — curse cures (see lib/debuffs CURE_ITEMS) ──────────
  antidote: {
    id: 'antidote',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 80,
    name: 'Antidote',
    description: 'A bitter herbal draught. Shortens whatever curse is on you.',
    rarity: 'common',
    icon: 'FlaskConical',
    type: 'consumable',
    maxStack: 256,
    value: 40,
  },
  bandage: {
    id: 'bandage',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 60,
    name: 'Bandage',
    description: 'Clean linen wrap. Eases a curse a little.',
    rarity: 'common',
    icon: 'Bandage',
    type: 'consumable',
    maxStack: 256,
    value: 25,
  },
  first_aid_kit: {
    id: 'first_aid_kit',
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 300,
    name: 'First Aid Kit',
    description: 'A stocked field kit. Shakes off a curse far faster than a bandage.',
    rarity: 'uncommon',
    icon: 'BriefcaseMedical',
    type: 'consumable',
    maxStack: 256,
    value: 120,
  },
  // ── M2D2 #1 — Common jewelry (equipped via store equipJewelry) ──
  ring: {
    id: 'ring',
    name: 'Ring',
    type: 'equipment',
    rarity: 'common',
    icon: 'Circle',
    maxStack: 1,
    value: 50,
    weightGrams: 20,
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    description: 'A plain iron band. +2% damage.',
    metadata: { jewelrySlot: 'ring', jewelryEffect: 'damage', jewelryValue: 0.02 },
  },
  necklace: {
    id: 'necklace',
    name: 'Necklace',
    type: 'equipment',
    rarity: 'common',
    icon: 'Gem',
    maxStack: 1,
    value: 80,
    weightGrams: 30,
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    description: 'A simple chain. +5% attack speed and rate of fire.',
    metadata: { jewelrySlot: 'necklace', jewelryEffect: 'speed', jewelryValue: 0.05 },
  },
  bracelet: {
    id: 'bracelet',
    name: 'Bracelet',
    type: 'equipment',
    rarity: 'common',
    icon: 'CircleDot',
    maxStack: 1,
    value: 60,
    weightGrams: 25,
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    description: 'A thin band. +2% maximum health.',
    metadata: { jewelrySlot: 'bracelet', jewelryEffect: 'health', jewelryValue: 0.02 },
  },
  // M2D4 #2 — PHASE 4: the boss drop. A five-slot legendary mage staff that
  // follows the same ITEMS shape as every other weapon; not sold, not in any
  // chest, and never in the starting inventory (drop-only).
  all_for_staff: {
    id: 'all_for_staff',
    mastery: 0,
    attackSpeed: 1.0,
    rateOfFireHold: 0,
    rateOfFireClick: 2.0,
    staminaUsage: 20,
    archetypeFit: 'mage',
    weightGrams: 1800,
    name: 'All For Staff',
    description: 'A legendary staff that bends every school of magic to its wielder: Destructor Purple, Pulsar, Imperium Glaciale, Hollow Cryfremag and Holy Tele.',
    rarity: 'legendary',
    icon: 'Sparkles',
    type: 'weapon',
    maxStack: 1,
    value: 5000,
    metadata: { weaponCategory: 'staff', damage: 10 },
  },
  // M2D5 #1 — Jimny's mining-equipment components. Placeable rig parts, not
  // consumables; actual Bytegold production is out of scope this session (the
  // items exist and can be bought, nothing mines yet).
  gpu: {
    id: 'gpu',
    name: 'GPU',
    description: 'A mid-tier graphics unit for a mining rig.',
    rarity: 'uncommon',
    icon: 'Cpu',
    type: 'equipment',
    maxStack: 64,
    value: 300,
    metadata: { miningComponent: 'gpu' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 1200,
  },
  rack: {
    id: 'rack',
    name: 'Rack',
    description: 'A mid-tier rig chassis that houses the mining components.',
    rarity: 'uncommon',
    icon: 'Server',
    type: 'equipment',
    maxStack: 64,
    value: 250,
    metadata: { miningComponent: 'rack' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 8000,
  },
  psu: {
    id: 'psu',
    name: 'PSU',
    description: 'A mid-tier power supply unit for a mining rig.',
    rarity: 'uncommon',
    icon: 'Plug',
    type: 'equipment',
    maxStack: 64,
    value: 200,
    metadata: { miningComponent: 'psu' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 2500,
  },
  cpu: {
    id: 'cpu',
    name: 'CPU',
    description: 'A mid-tier processor that schedules a mining rig.',
    rarity: 'uncommon',
    icon: 'Cpu',
    type: 'equipment',
    maxStack: 64,
    value: 350,
    metadata: { miningComponent: 'cpu' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 400,
  },
  asic: {
    id: 'asic',
    name: 'ASIC',
    description: 'A high-tier application-specific miner, far hungrier and far faster than a GPU.',
    rarity: 'epic',
    icon: 'CircuitBoard',
    type: 'equipment',
    maxStack: 64,
    value: 1500,
    metadata: { miningComponent: 'asic' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 900,
  },
  // M2D5 #1 — Bytechip arm implants. The authoritative ownership flag lives on
  // player.hasBytechip (store), so purchaseShopItem also sets it; the item
  // entry exists so Jimny's shop can list and price it.
  bytechip_l: {
    id: 'bytechip_l',
    name: 'Bytechip (L)',
    description: 'A left-arm Bytechip implant from the Bytegold network.',
    rarity: 'epic',
    icon: 'CircuitBoard',
    type: 'equipment',
    maxStack: 1,
    value: 400,
    metadata: { bytechipSide: 'L' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 450,
  },
  bytechip_r: {
    id: 'bytechip_r',
    name: 'Bytechip (R)',
    description: 'A right-arm Bytechip implant from the Bytegold network.',
    rarity: 'epic',
    icon: 'CircuitBoard',
    type: 'equipment',
    maxStack: 1,
    value: 400,
    metadata: { bytechipSide: 'R' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 450,
  },
  // M2D5 #1 — Bytecard: the broad name for the whole Bytegold system. Bytegold
  // itself is already a persisted player field (player.bytegold, minted only by
  // addBytegold); the Bytecard is added as a key item/token so the system has a
  // physical, purchasable representation.
  bytecard: {
    id: 'bytecard',
    name: 'Bytecard',
    description: 'A ledger card for the Bytegold network. Represents the whole Bytegold system.',
    rarity: 'rare',
    icon: 'CreditCard',
    type: 'key',
    maxStack: 1,
    value: 250,
    metadata: { currency: 'bytegold' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 50,
  },
  // M2D5 #1 — Computer Packs sold by Johnny. Bundled rig parts; the assembly /
  // unpacking behaviour does not exist this session.
  computer_pack_low: {
    id: 'computer_pack_low',
    name: 'Computer Pack (Low)',
    description: 'A bundled low-tier computer kit: enough to start a basic mining rig.',
    rarity: 'uncommon',
    icon: 'Package',
    type: 'equipment',
    maxStack: 1,
    value: 900,
    metadata: { miningComponent: 'pack', packTier: 'low' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 3000,
  },
  computer_pack_medium: {
    id: 'computer_pack_medium',
    name: 'Computer Pack (Medium)',
    description: 'A bundled mid-tier computer kit for a serious mining rig.',
    rarity: 'rare',
    icon: 'Package',
    type: 'equipment',
    maxStack: 1,
    value: 1800,
    metadata: { miningComponent: 'pack', packTier: 'medium' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 4500,
  },
  computer_pack_high: {
    id: 'computer_pack_high',
    name: 'Computer Pack (High)',
    description: 'A bundled high-tier computer kit built for heavy Bytegold mining.',
    rarity: 'epic',
    icon: 'Package',
    type: 'equipment',
    maxStack: 1,
    value: 3200,
    metadata: { miningComponent: 'pack', packTier: 'high' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 6000,
  },
  // M2D5 #1 — individual PC parts sold by Jimny (no assembly behaviour).
  ram: {
    id: 'ram',
    name: 'RAM',
    description: 'A stick of memory for a mining rig.',
    rarity: 'common',
    icon: 'MemoryStick',
    type: 'equipment',
    maxStack: 64,
    value: 150,
    metadata: { miningComponent: 'ram' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 200,
  },
  ssd: {
    id: 'ssd',
    name: 'SSD',
    description: 'A fast solid-state drive for a mining rig.',
    rarity: 'uncommon',
    icon: 'HardDrive',
    type: 'equipment',
    maxStack: 64,
    value: 250,
    metadata: { miningComponent: 'ssd' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 150,
  },
  hdd: {
    id: 'hdd',
    name: 'HDD',
    description: 'A cheap spinning-disk drive for bulk storage.',
    rarity: 'common',
    icon: 'HardDriveDownload',
    type: 'equipment',
    maxStack: 64,
    value: 120,
    metadata: { miningComponent: 'hdd' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 500,
  },
  case: {
    id: 'case',
    name: 'Case',
    description: 'A steel chassis that holds a mining rig together.',
    rarity: 'common',
    icon: 'Box',
    type: 'equipment',
    maxStack: 1,
    value: 180,
    metadata: { miningComponent: 'case' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 2000,
  },
  motherboard: {
    id: 'motherboard',
    name: 'Motherboard',
    description: 'The main board that ties every rig component together.',
    rarity: 'uncommon',
    icon: 'CircuitBoard',
    type: 'equipment',
    maxStack: 64,
    value: 220,
    metadata: { miningComponent: 'motherboard' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 600,
  },
  cpu_cooler: {
    id: 'cpu_cooler',
    name: 'CPU Cooler',
    description: 'A heatsink and fan that keeps a rig processor from cooking.',
    rarity: 'common',
    icon: 'Fan',
    type: 'equipment',
    maxStack: 64,
    value: 90,
    metadata: { miningComponent: 'cpu_cooler' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 400,
  },
  thermal_paste: {
    id: 'thermal_paste',
    name: 'Thermal Paste',
    description: 'A small tube of heat-transfer compound for rig assembly.',
    rarity: 'common',
    icon: 'Droplet',
    type: 'equipment',
    maxStack: 64,
    value: 30,
    metadata: { miningComponent: 'thermal_paste' },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 20,
  },
};

// M2D5 #1 — organ cyberware sold by Johnny. Derived from the authoritative
// CYBERWARE_SLOTS list so the shop and the Cyberware panel can never drift.
// Physical effects remain unimplemented placeholders (see lib/cyberware).
for (const slot of CYBERWARE_SLOTS) {
  ITEMS[`cyber_${slot.id}`] = {
    id: `cyber_${slot.id}`,
    name: `${slot.label} Cyberware`,
    description: `An organ cyberware implant for the ${slot.label.toLowerCase()}${slot.paired ? ' (paired, L/R)' : ''}. Physical effects are not yet implemented.`,
    rarity: 'rare',
    icon: 'Cpu',
    type: 'equipment',
    maxStack: 1,
    value: slot.paired ? 200 : 120,
    metadata: { cyberwareSlot: slot.id, paired: slot.paired },
    mastery: 0,
    attackSpeed: 0,
    rateOfFireHold: 0,
    rateOfFireClick: 0,
    staminaUsage: 0,
    archetypeFit: '',
    weightGrams: 500,
  };
}

const NAME_TO_ID: Record<string, string> = Object.values(ITEMS).reduce(
  (acc, item) => {
    acc[item.name.toLowerCase()] = item.id;
    return acc;
  },
  {} as Record<string, string>
);

export function getItem(id: string): ItemDef | undefined {
  return ITEMS[id];
}

export function getItemByName(name: string): ItemDef | undefined {
  const id = NAME_TO_ID[name.toLowerCase()];
  return id ? ITEMS[id] : undefined;
}

export function getItemIdByName(name: string): string | undefined {
  return NAME_TO_ID[name.toLowerCase()];
}

export function getAllItems(): ItemDef[] {
  return Object.values(ITEMS);
}
